# Generated by Django 3.1.1 on 2020-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='social_link',
            field=models.URLField(null=True),
        ),
    ]
