# Generated by Django 3.1.1 on 2020-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.project')),
                ('short', models.TextField()),
                ('stakeholders', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_problem_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_solution_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_stakeholders_description',
        ),
    ]
