# Generated by Django 3.1.1 on 2020-10-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200918_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
